### ISSUE TITLE
只要白名单里有一个程序进行读写文件，我hook他是不是就行了。

### ISSUE THREAD

**Issue by xuanxuanblingbling** [DaxiaSec/SXF_aTrust_sandbox_bypass#11]
不知道我的理解对不，就是这是个白名单机制，正常功能，目的为了落地文件到沙盒外，但是这个功能下的程序，运行时直接能访问沙盒内外的文件系统。所以只要白名单里有一个程序进行读写文件，并且我在沙盒内能进行调试或者hook，就应该能完成逃逸。如果按照这个理解，问题不在于是不是管理员添加一个白名单程序，关键在于我能不能对白名单程序的运行时进行篡改，或者说某个白名单程序有没有直接给文件系统路径写文件的功能（比如什么保存文件等等）。

**Comment by xuanxuanblingbling** [comment]
按上述理解，如果能调试的情况下，甚至都不需要白名单程序必须有读写文件的功能，可以把白名单程序当个壳，注入读写功能的代码。

**Comment by DaxiaSec** [comment]
谢谢探讨，我觉得这个思路很好，但具体没有试过，因为是黑盒且线上环境，时间有限，只是简单测试了几个场景，但理论上应该是可行的

**Comment by xuanxuanblingbling** [comment]
> 谢谢探讨，我觉得这个思路很好，但具体没有试过，因为是黑盒且线上环境，时间有限，只是简单测试了几个场景，但理论上应该是可行的

如果可行，那我觉得这必然是个洞，这个功能除非别用，只要你用了，只要白名单里面有一个程序，应该就能出去。甚至都可以安装一个任何带“打开”功能的程序测试一下，任意一个编辑器都行。

**Comment by DaxiaSec** [comment]
感谢您的指导，这是个非常好的思路，但由于是众测，目前已无环境
