### ISSUE TITLE
冤大头没给钱，恼羞成怒了，就开源了，小丑一个

### ISSUE THREAD

**Issue by ldwt** [DaxiaSec/SXF_aTrust_sandbox_bypass#12]
哈哈

**Comment by DaxiaSec** [comment]
赛博鼠，你上大号来对线好不好。
我说水壶可以喝水有啥问题？昨晚很多安全圈的朋友加我微信为我加油，我始终相信邪不压正，大家都看的清这是怎么回事。
什么样的人说什么样的话，你说厂商是冤大头，代表你潜意识就是想压榨厂商，而这次漏洞完全按照他们流程走，他们不说是正常功能，或者给了一毛钱，我也会承担对应的义务。

事实是，厂商不但认为是正常功能，而且冷暴力处理，我只是向大家介绍正常功能，何来恼羞成怒？ 只有赛博鼠这种对待中国公司没有下限的人，为了割韭菜不提交厂商或CNVD的人，才会没有原则、没有底线的曝光漏洞，也只有这种人会说出厂商给的赏金是封口费，压根忽视别人的劳动付出，也只有这样的人会说github是境外，至于他的小团体能出什么样的言论我压根不会觉得惊奇，至此。

**Comment by dem0ns** [comment]
> 哈哈

上来就开小号骂人？？？

**Comment by wuxiumu** [comment]
吃瓜吃瓜

**Comment by 01101sam** [comment]
有种把你大号GitHub Username发出来

**Comment by Popxie** [comment]
赛博鼠  小白帽  啥意思啊？？？求科普🤣

**Comment by yanwg0602** [comment]
赛博鼠 小白帽 啥意思啊？？？求科普🤣
