### ISSUE TITLE
来讨论下这算不算漏洞

### ISSUE THREAD

**Issue by closethe** [DaxiaSec/SXF_aTrust_sandbox_bypass#17]
1、如果沙箱内程序被禁止访问沙箱外文件，那么，这应该是个漏洞，毕竟沙箱对文件操作的隔离不完善。
2、这个反弹shell，说实话，是个笑话
3、没确认漏洞，就报2W，SXF就是个智障

**Comment by DaxiaSec** [comment]
他们说正常功能设计 那就正常功能设计啊 为什么报警说我是在境外平台公开漏洞呢？

**Comment by cdh1991** [comment]
这应该是刑事案件吧，要是有问题不会被放出来吧！

**Comment by 01101sam** [comment]
> 1、如果沙箱内程序被禁止访问沙箱外文件，那么，这应该是个漏洞，毕竟沙箱对文件操作的隔离不完善。 2、这个反弹shell，说实话，是个笑话 3、没确认漏洞，就报2W，SXF就是个智障

可能人家一开始就打算白嫖漏洞，先报价格让你提交漏洞详细，然后收了报告修好后就说不要了（
